theme: jekyll-theme-minimal
title: Kim Johnston
author: Kim Johnston
locale: en_GB
lang: en_GB
logo: /assets/img/kim-reverse.svg
facebook:
  publisher: kim.johnston.370515
social:
  name: Kim Johnston
  links:
    - https://www.facebook.com/kim.johnston.370515
